### ISSUE TITLE
Some Semaphore v3 functions don't work with some of the latest versions of Chrome

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/extensions#9] opened 2024-05-02 16:21 UTC
## Description

The Semaphore v3 functions related to proof generation and verification don't work with some of the latest versions of Chrome. 

<img width="752" alt="Screenshot 2024-05-02 at 6 23 46 PM" src="https://github.com/semaphore-protocol/extensions/assets/52170174/3911d8db-4e19-46d1-83d0-a44adce03863">

## Tools

Chrome: `Version 124.0.6367.119 (Official Build) (arm64)`

## Reproduce the error

Go to https://benchmarks.semaphore.pse.dev/ and try to run Semaphore v3 functions. You should see the error in the browser console.

**Comment by emirsoyturk** [comment] 2024-05-20 08:49
@vplasencia I would like to take on this issue. Could you please assign it to me?

**Comment by vplasencia** [comment] 2024-05-20 11:22
Hey @emirsoyturk!

I just assigned you this issue. Thank you. Please let us know if you have any questions.

**Comment by emirsoyturk** [comment] 2024-05-20 12:08
Hey @vplasencia,

The error disappears when I disable CORS in Chrome using the following command:

```bash
open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/chrome-dev-disabled-security" --disable-web-security
```

This indicates the issue is likely related to CORS policy enforcement. It's probably due to the backend of [https://www.trusted-setup-pse.org](https://www.trusted-setup-pse.org) not including the necessary CORS headers.

Thanks!

**Comment by glamperd** [comment] 2024-05-21 05:49
I've added a CORS configuration to the S3 bucket that stores these files. See if that solves the issue.
I've allowed GET from any location (i.e. '*'). Is there any reason to restrict that?

**Comment by emirsoyturk** [comment] 2024-05-21 06:44
Hey @glamperd.

Now it works for both Chrome and Brave.

**Comment by glamperd** [comment] 2024-05-21 06:46
OK, great. I'll leave the settings like that unless we find other problems.

**Comment by vplasencia** [comment] 2024-05-22 08:18
Hey @emirsoyturk and @glamperd! Thank you very much for the updates.

It's still not working for me. It works in Firefox, but not in Chrome. The only difference I see is that the response header in Firefox has `access-control-allow-origin: *` and Chrome does not have it.

**Comment by emirsoyturk** [comment] 2024-05-22 08:54
@vplasencia, apparently Chrome cached the request, so I initially thought it was fixed. However, after clearing the cache and trying again, I believe the problem is still related to CORS. For example, when I enable the [Allow CORS: Access-Control-Allow-Origin](https://chromewebstore.google.com/detail/lhobafahddgcelffkeicbaginigeejlf) extension, it works normally.

**Comment by vplasencia** [comment] 2024-05-22 09:06
@emirsoyturk nice. Thanks. Makes sense. Yes, it looks like the problem is related to cors and the header response. I tried the extension you just shared and it worked when fetching the wasm file but it didn't work when fetching the zkey file.

**Comment by vplasencia** [comment] 2024-06-03 20:40
Hey @emirsoyturk @glamperd 

It's working now. More people also tried it and it's working fine. Thank you very much 🙏

**Comment by vplasencia** [comment] 2024-06-03 20:41
@gitpoap-bot @emirsoyturk

**Comment by vplasencia** [comment] 2024-06-03 20:43
Thank you very much for the contribution, I hope you like this POAP.

@gitpoap-bot @glamperd

**Closed** 2024-06-03 20:43 UTC
Labels: bug 🐛, good first issue
